project:
  type: website
  output-dir: docs

website:
  navbar:
    right:
      - text: "About"
        file: index.qmd
      - text: "CV"
        file: CV_CarlosGPoses.pdf
      - publications.qmd
  page-footer: 
    center: "© Copyright 2024 Carlos G. Poses"
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual

